/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MotoristaController;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Motorista;
import model.exceptions.MotoristaException;
import model.gerador.GeradorDeSenha;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 * @author mateu
 */
public class FrCadMotorista extends javax.swing.JFrame {

    ArrayList<Motorista> lst = new ArrayList();
    MotoristaController motoristaController;
    int idMotoristaEditando;
    static int idPrefeitura;

    /**
     * Creates new form FrCadMotorista
     */
    public FrCadMotorista(int idPrefeituraa) {
        initComponents();
        motoristaController = new MotoristaController();
        motoristaController.atualizarTabela(grdMotorista, idPrefeituraa);
        this.PreencheHoras();
        this.PreencheMinutos();
        this.habDesCampos(false);
        edtCarteira.addItem("B");
        edtCarteira.addItem("C");
        edtCarteira.addItem("D");
        edtCarteira.addItem("E");

    }

    public void PreencheMinutos() {
        for (int i = 0; i <= 59; i++) {
            if (i <= 9) {
                edtInicioMin.addItem("0" + Integer.toString(i));
                edtFimMinutos.addItem("0" + Integer.toString(i));
            } else {
                edtInicioMin.addItem(Integer.toString(i));
                edtFimMinutos.addItem(Integer.toString(i));
            }
        }
    }

    public void PreencheHoras() {
        for (int i = 0; i <= 24; i++) {
            if (i <= 9) {
                edtInicioHora.addItem("0" + Integer.toString(i));
                edtFimHoras.addItem("0" + Integer.toString(i));
            } else {
                edtInicioHora.addItem(Integer.toString(i));
                edtFimHoras.addItem(Integer.toString(i));
            }
        }
    }

    public void preencherCampos(Motorista m) {
        edtNome.setText(m.getNome());
        edtCpf.setText(m.getCpf());
        edtDataNascimento.setDate(m.getDataNascimento());
        edtEmail.setText(m.getEmail());
        edtSexo.setText(m.getSexo());
        edtRemuneracaoMensal.setText(String.valueOf(m.getRemuneracaoMensal()));
        edtInicioHora.setSelectedIndex(m.getHoraDeEntrada().getHours());
        edtInicioMin.setSelectedIndex(m.getHoraDeEntrada().getMinutes());
        edtFimHoras.setSelectedIndex(m.getHoraDeSaida().getHours());
        edtFimMinutos.setSelectedIndex(m.getHoraDeSaida().getMinutes());
    }

    public void habDesCampos(boolean flag) {
        edtNome.setEnabled(flag);
        edtEmail.setEnabled(flag);
        edtInicioHora.setEnabled(flag);
        edtInicioMin.setEnabled(flag);
        edtFimHoras.setEnabled(flag);
        edtFimMinutos.setEnabled(flag);
        edtCpf.setEnabled(flag);
        edtSexo.setEnabled(flag);
        edtRemuneracaoMensal.setEnabled(flag);
        edtCarteira.setEditable(flag);
    }

    public void limparCampos() {
        edtNome.setText("");
        edtEmail.setText("");
        edtInicioHora.setSelectedIndex(0);
        edtInicioMin.setSelectedIndex(0);
        edtFimHoras.setSelectedIndex(0);
        edtFimMinutos.setSelectedIndex(0);
        edtCpf.setText("");
        edtSexo.setText("");
        edtRemuneracaoMensal.setText("");
        edtCarteira.setSelectedIndex(0);
        edtDataNascimento.setDate(new Date());
    }

    private Object getObjectSelectOnGrid() {
        int rowClicked = grdMotorista.getSelectedRow();
        Object obj = null;
        if (rowClicked >= 0) {
            obj = grdMotorista.getModel().getValueAt(rowClicked, -1);
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        lblJornadaDeTrabalho = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        edtInicioHora = new javax.swing.JComboBox<>();
        lblHoras = new javax.swing.JLabel();
        edtInicioMin = new javax.swing.JComboBox<>();
        lblMin = new javax.swing.JLabel();
        edtFimHoras = new javax.swing.JComboBox<>();
        edtFimMinutos = new javax.swing.JComboBox<>();
        lblHorasFim = new javax.swing.JLabel();
        lblMinutosFim = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        edtSexo = new javax.swing.JTextField();
        edtCpf = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        edtDataNascimento = new com.toedter.calendar.JDateChooser();
        lblRemuneracaoMensal = new javax.swing.JLabel();
        edtRemuneracaoMensal = new javax.swing.JTextField();
        lblDiasDeTrabalho = new javax.swing.JLabel();
        edtSegunda = new java.awt.Checkbox();
        edtTerca = new java.awt.Checkbox();
        edtQuarta = new java.awt.Checkbox();
        edtQuinta = new java.awt.Checkbox();
        edtSexta = new java.awt.Checkbox();
        edtSabado = new java.awt.Checkbox();
        edtDomingo = new java.awt.Checkbox();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdMotorista = new javax.swing.JTable();
        lblCategoriaCarteira = new javax.swing.JLabel();
        edtCarteira = new javax.swing.JComboBox<>();
        bnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Motorista");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/novo_32x32.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/edit3_32x32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/del_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        lblEmail.setText("Email");

        lblJornadaDeTrabalho.setText("Jornada de Trabalho");

        lblInicio.setText("Inicio");

        lblFim.setText("Fim");

        lblHoras.setText("Horas");

        edtInicioMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        lblMin.setText("Minutos");

        lblHorasFim.setText("Horas");

        lblMinutosFim.setText("Minutos");

        lblCpf.setText("CPF");

        lblSexo.setText("Sexo");

        lblDataNascimento.setText("Data de Nascimento");

        lblRemuneracaoMensal.setText("Remuneração Mensal");

        lblDiasDeTrabalho.setText("Dias de Trabalho");

        edtSegunda.setLabel("Segunda-feira");

        edtTerca.setLabel("Terça-feira");

        edtQuarta.setLabel("Quarta-feira");

        edtQuinta.setLabel("Quinta-feira");

        edtSexta.setLabel("Sexta-feira");

        edtSabado.setLabel("Sábado");

        edtDomingo.setLabel("Domingo");

        grdMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(grdMotorista);

        lblCategoriaCarteira.setText("Categoria da carteira");

        edtCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCarteiraActionPerformed(evt);
            }
        });

        bnVoltar.setText("Voltar");
        bnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addGap(18, 18, 18)
                                .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(lblJornadaDeTrabalho)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(edtFimHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblInicio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(edtInicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHoras)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(edtInicioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblHorasFim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(edtFimMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMin)
                                    .addComponent(lblMinutosFim)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiasDeTrabalho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edtTerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblRemuneracaoMensal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtRemuneracaoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(edtQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edtSexta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(edtSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCategoriaCarteira)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(bnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnEditar)
                            .addComponent(btnExcluir)
                            .addComponent(btnSalvar)
                            .addComponent(btnCancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNome)
                                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmail)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpf)
                            .addComponent(lblSexo)
                            .addComponent(edtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJornadaDeTrabalho)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInicio)
                            .addComponent(edtInicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoras)
                            .addComponent(edtInicioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFim)
                            .addComponent(edtFimHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtFimMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorasFim)
                            .addComponent(lblMinutosFim))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataNascimento)
                            .addComponent(edtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRemuneracaoMensal)
                                .addComponent(edtRemuneracaoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCategoriaCarteira)
                                .addComponent(edtCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDiasDeTrabalho)
                            .addComponent(edtSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtTerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtSexta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(edtSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnVoltar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habDesCampos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void edtCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCarteiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCarteiraActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Motorista motoristaEditando = (Motorista) this.getObjectSelectOnGrid();

        if (motoristaEditando == null) {
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela");
        } else {
            this.limparCampos();
            this.habDesCampos(true);
            this.preencherCampos(motoristaEditando);
            idMotoristaEditando = motoristaEditando.getId();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habDesCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Motorista motoristaEditando = (Motorista) this.getObjectSelectOnGrid();

        if (motoristaEditando == null) {
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela");
        } else {
            try {
                Object[] options = {"Sim", "Não"};
                int opcao = JOptionPane.showOptionDialog(null, "Deseja mesmo excluir o motorista " + motoristaEditando.getNome() + " ?",
                         "Confirmação de exclusão", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
                if (opcao == 0) {
                    motoristaController.excluirMotorista(motoristaEditando);
                    motoristaController.atualizarTabela(grdMotorista, idPrefeitura);
                    JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso");
                } else if (opcao == 1) {
                    JOptionPane.showMessageDialog(this, "Exclusão cancelada!");
                    this.habDesCampos(false);
                }
            } catch (MotoristaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            Date horaInicio = new Date();
                Date horaFim = new Date();
                horaInicio.setHours(edtInicioHora.getSelectedIndex());
                horaInicio.setMinutes(edtInicioMin.getSelectedIndex());
                horaFim.setHours(edtFimHoras.getSelectedIndex());
                horaFim.setMinutes(edtFimMinutos.getSelectedIndex());
                ArrayList diasTrabalhados = new ArrayList();
                diasTrabalhados.add(edtSegunda.getState());
                diasTrabalhados.add(edtTerca.getState());
                diasTrabalhados.add(edtQuarta.getState());
                diasTrabalhados.add(edtQuinta.getState());
                diasTrabalhados.add(edtSexta.getState());
                diasTrabalhados.add(edtSabado.getState());
                diasTrabalhados.add(edtDomingo.getState());
                Double remuneracao = Double.parseDouble(edtRemuneracaoMensal.getText());
            if(idMotoristaEditando > 0){
                motoristaController.atualizarMotorista(idMotoristaEditando, edtNome.getText(), edtEmail.getText(),edtCpf.getText(),edtSexo.getText(), edtDataNascimento.getDate(), remuneracao, horaInicio, horaFim, (String) edtCarteira.getSelectedItem(), idPrefeitura);
            }else {
                String senha = GeradorDeSenha.geradorDeSenha();
                motoristaController.cadastrarMotorista(idMotoristaEditando, edtNome.getText(), edtEmail.getText(),edtCpf.getText(),edtSexo.getText(), edtDataNascimento.getDate(), remuneracao, horaInicio, horaFim, (String) edtCarteira.getSelectedItem(), senha, idPrefeitura);
            }
            
            motoristaController.atualizarTabela(grdMotorista, idPrefeitura);
            this.habDesCampos(false);
            this.limparCampos();
        }catch(MotoristaException e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        String EmailRemetente = "mailColetaDeLixo@gmail.com";
        String senhaEmailRemetente = "qxdvdtyjaztzcjgt";
        
        SimpleEmail email = new SimpleEmail();
        email.setHostName("smtp.gmail.com");
        email.setSmtpPort(465);
        email.setAuthentication(EmailRemetente, senhaEmailRemetente);
        email.setSSLOnConnect(true);
        
        try{
            email.setFrom(EmailRemetente);
            email.setSubject("Seus dados de login para acessar o sistema");
            email.setMsg("Teste inicial");
            email.addTo(EmailRemetente);
            email.send();
            System.out.println("Email foi enviado com sucesso");
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void bnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnVoltarActionPerformed
        FrPrefeitura telaPrefeitura = new FrPrefeitura();
        this.setVisible(false);
    }//GEN-LAST:event_bnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadMotorista(idPrefeitura).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnVoltar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> edtCarteira;
    private javax.swing.JTextField edtCpf;
    private com.toedter.calendar.JDateChooser edtDataNascimento;
    private java.awt.Checkbox edtDomingo;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JComboBox<String> edtFimHoras;
    private javax.swing.JComboBox<String> edtFimMinutos;
    private javax.swing.JComboBox<String> edtInicioHora;
    private javax.swing.JComboBox<String> edtInicioMin;
    private javax.swing.JTextField edtNome;
    private java.awt.Checkbox edtQuarta;
    private java.awt.Checkbox edtQuinta;
    private javax.swing.JTextField edtRemuneracaoMensal;
    private java.awt.Checkbox edtSabado;
    private java.awt.Checkbox edtSegunda;
    private javax.swing.JTextField edtSexo;
    private java.awt.Checkbox edtSexta;
    private java.awt.Checkbox edtTerca;
    private javax.swing.JTable grdMotorista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoriaCarteira;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblDiasDeTrabalho;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblHorasFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblJornadaDeTrabalho;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMinutosFim;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRemuneracaoMensal;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
