/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DepositoController;
import controller.LixeiroController;
import controller.MaterialController;
import controller.MotoristaController;
import controller.RotaController;
import java.util.ArrayList;
import java.util.List;
import model.Deposito;
import model.Lixeiro;
import model.Material;
import model.Motorista;
import static view.FrCadMotorista.idPrefeitura;

/**
 *
 * @author mateu
 */
public class FrCadRota extends javax.swing.JFrame {

    ArrayList<Motorista> lstMotorista = new ArrayList();
    MotoristaController motoristaController;
    ArrayList<Lixeiro> lstLixeiro = new ArrayList();
    LixeiroController lixeiroController;
    ArrayList<Material> lstMaterial = new ArrayList();
    MaterialController materialController;
    DepositoController depositoController;
    ArrayList<Deposito> lstDeposito = new ArrayList();
    ArrayList<Deposito> lstFiltrada = new ArrayList();
    int idRotaEditando;
    static int idPrefeitura;
    RotaController rotaController;

    /**
     * Creates new form FrCadRota
     */
    public FrCadRota(int idPrefeituraa) {
        initComponents();
        rotaController = new RotaController();
        motoristaController = new MotoristaController();
        lstMotorista = (ArrayList<Motorista>) motoristaController.atualizaMotoristas(idPrefeituraa);
        edtMotorista.addItem("");
        for (int i = 0; i < lstMotorista.size(); i++) {
            edtMotorista.addItem(lstMotorista.get(i).getNome());
        }
        lixeiroController = new LixeiroController();
        lstLixeiro = (ArrayList<Lixeiro>) lixeiroController.atualizaLixeiros(idPrefeituraa);
        edtLixeiro.addItem("");
        for (int i = 0; i < lstLixeiro.size(); i++) {
            edtLixeiro.addItem(lstLixeiro.get(i).getNome());
        }
        materialController = new MaterialController();
        edtMaterial.addItem("");
        lstMaterial = (ArrayList<Material>) materialController.atualizarListaMateriaisAceitos(idPrefeituraa);
        for (int i = 0; i < lstMaterial.size(); i++) {
            edtMaterial.addItem(lstMaterial.get(i).getNome());
        }
        depositoController = new DepositoController();
        lstDeposito = (ArrayList<Deposito>) depositoController.atualizaDepositos(idPrefeituraa);
        rotaController.atualizarTabela(grdRota, idPrefeituraa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblOrigem = new javax.swing.JLabel();
        edtOrigem = new javax.swing.JTextField();
        lblDestino = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        edtMaterial = new javax.swing.JComboBox<>();
        lblQuantidadeMaterial = new javax.swing.JLabel();
        edtQuantidadeMaterial = new javax.swing.JTextField();
        lblMotorista = new javax.swing.JLabel();
        edtMotorista = new javax.swing.JComboBox<>();
        lblData = new javax.swing.JLabel();
        lblLixeiro = new javax.swing.JLabel();
        edtLixeiro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdRota = new javax.swing.JTable();
        edtData = new com.toedter.calendar.JDateChooser();
        edtDestino = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Rota");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/novo_32x32.png"))); // NOI18N
        btnNovo.setText("Novo");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/edit3_32x32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/del_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoColetaDeLixoImagens/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblOrigem.setText("Origem");

        lblDestino.setText("Destino");

        lblMaterial.setText("Material");

        edtMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                edtMaterialItemStateChanged(evt);
            }
        });
        edtMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edtMaterialMouseClicked(evt);
            }
        });
        edtMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMaterialActionPerformed(evt);
            }
        });

        lblQuantidadeMaterial.setText("Quantidade de Material");

        lblMotorista.setText("Motorista");

        edtMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMotoristaActionPerformed(evt);
            }
        });

        lblData.setText("Data");

        lblLixeiro.setText("Lixeiro");

        grdRota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(grdRota);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLixeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtLixeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtMotorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOrigem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMaterial)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQuantidadeMaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtQuantidadeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigem)
                    .addComponent(edtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino)
                    .addComponent(edtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaterial)
                        .addComponent(edtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblQuantidadeMaterial)
                        .addComponent(edtQuantidadeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblData))
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotorista)
                    .addComponent(edtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLixeiro)
                    .addComponent(edtLixeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMotoristaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(idRotaEditando > 0){
            rotaController.atualizarRota(idRotaEditando, edtOrigem.getText(), 
                    lstFiltrada.get(edtDestino.getSelectedIndex()), 
                    lstMaterial.get(edtMaterial.getSelectedIndex()-1), 
                    Double.parseDouble(edtQuantidadeMaterial.getText()), 
                    edtData.getDate(), lstLixeiro.get(edtLixeiro.getSelectedIndex()), 
                    lstMotorista.get(edtMotorista.getSelectedIndex()), idPrefeitura);
        }else{
            rotaController.cadastrarRota(idRotaEditando, edtOrigem.getText(), 
                    lstFiltrada.get(edtDestino.getSelectedIndex()), 
                    lstMaterial.get(edtMaterial.getSelectedIndex() - 1), 
                    Double.parseDouble(edtQuantidadeMaterial.getText()), 
                    edtData.getDate(), lstLixeiro.get(edtLixeiro.getSelectedIndex() - 1), 
                    lstMotorista.get(edtMotorista.getSelectedIndex() - 1), idPrefeitura);
        }
        rotaController.atualizarTabela(grdRota, idPrefeitura);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_edtMaterialItemStateChanged

    }//GEN-LAST:event_edtMaterialItemStateChanged

    private void edtMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edtMaterialMouseClicked

    }//GEN-LAST:event_edtMaterialMouseClicked

    private void edtMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMaterialActionPerformed
        edtDestino.removeAllItems();
        if (edtMaterial.getSelectedIndex() != 0) {
            lstFiltrada.clear();
            int idMaterial = lstMaterial.get(edtMaterial.getSelectedIndex() - 1).getId();
            System.out.println("Tamanho lista deposito " + lstDeposito.size());
            for (int i = 0; i < lstDeposito.size(); i++) {
                System.out.println("Passei aqui " + i + " vezes");
                Deposito deposito = lstDeposito.get(i);
                System.out.println("deposito.getMaterial " + deposito.getMaterial());
                for (Material m : deposito.getMaterial()) {
                    if (m.getId() == idMaterial) {
                        lstFiltrada.add(deposito);
                        edtDestino.addItem(deposito.getNome());
                        System.out.println("cheguei dentro do if");
                    }

                }
                //edtDestino.addItem(lstDeposito.get(i).getNome());
            }//buscarDestinoComMateriais
        }
        System.out.println("opcao selecionada " + edtMaterial.getSelectedItem());
    }//GEN-LAST:event_edtMaterialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrPrefeitura telaPrefeitura = new FrPrefeitura(idPrefeitura);
        telaPrefeitura.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadRota(idPrefeitura).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private com.toedter.calendar.JDateChooser edtData;
    private javax.swing.JComboBox<String> edtDestino;
    private javax.swing.JComboBox<String> edtLixeiro;
    private javax.swing.JComboBox<String> edtMaterial;
    private javax.swing.JComboBox<String> edtMotorista;
    private javax.swing.JTextField edtOrigem;
    private javax.swing.JTextField edtQuantidadeMaterial;
    private javax.swing.JTable grdRota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblLixeiro;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblMotorista;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblQuantidadeMaterial;
    // End of variables declaration//GEN-END:variables
}
